#ifndef RUNTIME_H
#define RUNTIME_H

const char* BIOS =
"local t = 0\n"
"function visuals()\n"
    "t = t + 0.002\n"
    "local cx, cy = 64, 44\n"
    "for i = 32, 1, -1 do\n"
        "local r = i * 4\n"
        "local wave_x = sin(t + i * 0.1) * 15\n"
        "local wave_y = cos(t * 0.8 + i * 0.15) * 10\n"
        "local pulse = r + sin(t * 2 + i * 0.3) * 6\n"
        "local col = 1 + flr((i + t * 10) % 15)\n"
        "circfill(cx + flr(wave_x), cy + flr(wave_y), flr(pulse), col)\n"
    "end\n"
"end\n"
"function _tick()\n"
	"cls(0)\n"
	"visuals()\n"
	"local black = rgb(0,0,0)\n"
	"rectfill(36, 42, 89, 50, black)\n"
	"text(\"no cassette\", 38, 44, 13)\n"
"end\n";

// hell yeah i got a script for this u got me messed up u think im typing allat shi, again.
const char* EYECANDY_SOURCE = 
"-- runtime/graphics.lua\n"
"local ADDR_FB   = 0x00000 --\n"
"local ADDR_FONT = 0x06200 --\n"
"local FB_WID    = 128     --\n"
"local FB_HEI    = 96      --\n"
"local ADDR_BANK_SWITCH = 0x06044 --\n"
"local PALETTE = {}\n"
"\n"
"-- Persistent tracking tables for sprite bank metadata\n"
"local BANK_ADDRESSES = {\n"
"    [0] = 0x06500,        	  -- Bank 0 baseline RAM address\n"
"    [1] = 0x08500, 		  	  -- Bank 1 baseline RAM address (shifted past a full 64*64 block)\n"
"}\n"
"local BANK_WIDTHS  = { [0] = 64, [1] = 64 } -- Defaults\n"
"local BANK_HEIGHTS = { [0] = 64, [1] = 64 } -- Defaults\n"
"\n"
"-- Global Camera Tracking States (Defaults to 0, 0)\n"
"local CAM_X = 0\n"
"local CAM_Y = 0\n"
"\n"
"-- Global Clipping Rect tracking (Defaults to full-screen bounds)\n"
"local CLIP = false\n"
"local CLIP_X0 = 0\n"
"local CLIP_Y0 = 0\n"
"local CLIP_X1 = FB_WID - 1\n"
"local CLIP_Y1 = FB_HEI - 1\n"
"\n"
"-- Helper: Packs 0-255 RGB channels into a single 16-bit RGB565 integer\n"
"function rgb(r, g, b)\n"
"    local r5 = math.floor((r * 31) / 255)\n"
"    local g6 = math.floor((g * 63) / 255)\n"
"    local b5 = math.floor((b * 31) / 255)\n"
"    return (r5 * 2048) + (g6 * 32) + b5\n"
"end\n"
"\n"
"local PALETTE = {\n"
"  [0] = rgb(23, 25, 27), 		-- asphalt\n"
"  [1] = rgb(40, 35, 123), 		-- ocean\n"
"  [2] = rgb(50, 89, 226), 		-- afternoon\n"
"  [3] = rgb(51, 165, 255), 		-- neon\n"
"  [4] = rgb(10, 75, 77), 		-- rainforest\n"
"  [5] = rgb(114, 203, 37), 		-- bamboo\n"
"  [6] = rgb(255, 196, 56), 		-- solar\n"
"  [7] = rgb(240, 108, 0), 		-- tangerine\n"
"  [8] = rgb(209, 40, 65), 		-- strawberry\n"
"  [9] = rgb(87, 20, 46), 		-- cherry\n"
"  [10] = rgb(151, 63, 63), 		-- soil\n"
"  [11] = rgb(241, 194, 132), 	        -- caucasian\n"
"  [12] = rgb(229, 93, 172), 		-- bubblegum\n"
"  [13] = rgb(241, 240, 238), 	        -- white\n"
"  [14] = rgb(150, 165, 171), 	        -- cobblestone\n"
"  [15] = rgb(88, 108, 121), 		-- clay\n"
"}\n"
"\n"
"-- primitve functions\n"
"function cls(color)\n"
"    if PALETTE[color] then\n"
"        color = PALETTE[color]\n"
"    end\n"
"\n"
"    local low_byte  = color & 0xFF\n"
"    local high_byte = (color >> 8) & 0xFF\n"
"   \n"
"    for addr = ADDR_FB, ADDR_FB + 24575, 2 do\n"
"        poke(addr,     low_byte)\n"
"        poke(addr + 1, high_byte)\n"
"    end\n"
"end\n"
"\n"
"function pset(x, y, color)\n"
"    -- Integer representation\n"
"    x = x // 1\n"
"    y = y // 1\n"
"\n"
"	-- Apply the global camera displacement offset!\n"
"    x = x - CAM_X -- this is basically cheap but idc anymore\n"
"    y = y - CAM_Y\n"
"    \n"
"    -- 2. Hardware Clipping Check\n"
"    -- If a custom clip window is active, drop pixels outside it!\n"
"    if CLIP then\n"
"        if x < CLIP_X0 or x > CLIP_X1 or y < CLIP_Y0 or y > CLIP_Y1 then \n"
"            return \n"
"        end\n"
"    end\n"
"    \n"
"    if x < 0 or x >= FB_WID or y < 0 or y >= FB_HEI then return end\n"
"\n"
"    if PALETTE[color] then\n"
"        color = PALETTE[color]\n"
"    end\n"
" \n"
"    local pixel_addr = ADDR_FB + ((y * FB_WID + x) * 2)\n"
"    \n"
"    local low_byte  = color & 0xFF\n"
"    local high_byte = (color >> 8) & 0xFF\n"
"    \n"
"    poke(pixel_addr,     low_byte)\n"
"    poke(pixel_addr + 1, high_byte)\n"
"end\n"
"\n"
"function pget(x, y)\n"
"    if x >= 0 and x < 128 and y >= 0 and y < 96 then\n"
"        local addr = 0x00000 + (y * 128) + x\n"
"        peek(addr)\n"
"    end\n"
"end\n"
"\n"
"function rectfill(x0, y0, x1, y1, color)\n"
"    -- Standardize bounds sorting (handles drawing backwards cleanly)\n"
"    local start_x = math.min(x0, x1)\n"
"    local end_x = math.max(x0, x1)\n"
"    local start_y = math.min(y0, y1)\n"
"    local end_y = math.max(y0, y1)\n"
"    \n"
"    -- Hard clipping boundaries protection\n"
"    if start_x < 0 then start_x = 0 end\n"
"    if end_x > 127 then end_x = 127 end\n"
"    if start_y < 0 then start_y = 0 end\n"
"    if end_y > 95 then end_y = 95 end\n"
"\n"
"    -- Optimize by running pset loop directly \n"
"    for y = start_y, end_y do\n"
"        for x = start_x, end_x do\n"
"            pset(x, y, color)\n"
"        end\n"
"    end\n"
"end\n"
"\n"
"function rect(x0, y0, x1, y1, color)\n"
"    -- Draw a wireframe rectangle using four straight lines or fills\n"
"    rectfill(x0, y0, x1, y0, color) -- Top edge\n"
"    rectfill(x0, y1, x1, y1, color) -- Bottom edge\n"
"    rectfill(x0, y0, x0, y1, color) -- Left edge\n"
"    rectfill(x1, y0, x1, y1, color) -- Right edge\n"
"end\n"
"\n"
"function line(x0, y0, x1, y1, color)\n"
"    x0, y0, x1, y1 = math.floor(x0), math.floor(y0), math.floor(x1), math.floor(y1)\n"
"    local dx = math.abs(x1 - x0)\n"
"    local dy = math.abs(y1 - y0)\n"
"    local sx = x0 < x1 and 1 or -1\n"
"    local sy = y0 < y1 and 1 or -1\n"
"    local err = dx - dy\n"
"\n"
"    while true do\n"
"        pset(x0, y0, color)\n"
"        \n"
"        if x0 == x1 and y0 == y1 then break end\n"
"        \n"
"        local e2 = 2 * err\n"
"        if e2 > -dy then\n"
"            err = err - dy\n"
"            x0 = x0 + sx\n"
"        end\n"
"        if e2 < dx then\n"
"            err = err + dx\n"
"            y0 = y0 + sy\n"
"        end\n"
"    end\n"
"end\n"
"\n"
"function circ(cx, cy, r, col)\n"
"    -- Integer representation\n"
"    cx = cx // 1\n"
"    cy = cy // 1\n"
"	\n"
"    -- Clamp negative radii safely\n"
"    if r < 0 then return end\n"
"    \n"
"    -- Handle the trivial radius 0 case (single pixel)\n"
"    if r == 0 then\n"
"        pset(cx, cy, col)\n"
"        return\n"
"    end\n"
"\n"
"    local x = 0\n"
"    local y = r\n"
"    local d = 3 - (2 * r) -- Initial decision parameter\n"
"\n"
"    -- Helper local function to mirror the 8 symmetrical octants cleanly\n"
"    local function plot8(x, y)\n"
"    		\n"
"        pset(cx + x, cy + y, col)\n"
"        pset(cx - x, cy + y, col)\n"
"        pset(cx + x, cy - y, col)\n"
"        pset(cx - x, cy - y, col)\n"
"        pset(cx + y, cy + x, col)\n"
"        pset(cx - y, cy + x, col)\n"
"        pset(cx + y, cy - x, col)\n"
"        pset(cx - y, cy - x, col)\n"
"    end\n"
"\n"
"    plot8(x, y)\n"
"\n"
"    while x <= y do\n"
"        x = x + 1\n"
"        \n"
"        if d > 0 then\n"
"            y = y - 1\n"
"            d = d + 4 * (x - y) + 10\n"
"        else\n"
"            d = d + (4 * x) + 6\n"
"        end\n"
"        \n"
"        plot8(x, y)\n"
"    end\n"
"end\n"
"\n"
"function circfill(cx, cy, r, color)\n"
"    cx, cy, r = math.floor(cx), math.floor(cy), math.floor(r)\n"
"    if r < 0 then return end\n"
"    \n"
"    local x = r\n"
"    local y = 0\n"
"    local err = 1 - r\n"
"\n"
"    while x >= y do\n"
"        -- Draw horizontal bars across the circle quadrants to fill it cleanly\n"
"        line(cx - x, cy + y, cx + x, cy + y, color)\n"
"        line(cx - x, cy - y, cx + x, cy - y, color)\n"
"        line(cx - y, cy + x, cx + y, cy + x, color)\n"
"        line(cx - y, cy - x, cx + y, cy - x, color)\n"
"\n"
"        y = y + 1\n"
"        if err < 0 then\n"
"            err = err + 2 * y + 1\n"
"        else\n"
"            x = x - 1\n"
"            err = err + 2 * (y - x) + 1\n"
"        end\n"
"    end\n"
"end\n"
"\n"
"function camera(x, y)\n"
"    -- If no parameters are passed, reset the camera back to origin (0, 0)\n"
"    CAM_X = math.floor(x or 0)\n"
"    CAM_Y = math.floor(y or 0)\n"
"end\n"
"\n"
"function clip(x, y, w, h)\n"
"    if not x or not y or not w or not h then\n"
"        -- Clear the clip: turn it off and reset to screen size\n"
"        CLIP    = false\n"
"        CLIP_X0 = 0\n"
"        CLIP_Y0 = 0\n"
"        CLIP_X1 = FB_WID - 1\n"
"        CLIP_Y1 = FB_HEI - 1\n"
"    else\n"
"        -- Engage the clip bounding region\n"
"        CLIP    = true\n"
"        CLIP_X0 = math.floor(x)\n"
"        CLIP_Y0 = math.floor(y)\n"
"        CLIP_X1 = math.floor(x + w - 1)\n"
"        CLIP_Y1 = math.floor(y + h - 1)\n"
"    end\n"
"end\n"
"\n"
"-- texture/sprite handling\n"
"local function unpack_uint32(str, offset)\n"
"    local b1, b2, b3, b4 = string.byte(str, offset, offset + 3)\n"
"    return b1 + (b2 << 8) + (b3 << 16) + (b4 << 24)\n"
"end\n"
"\n"
"local function unpack_int32(str, offset)\n"
"    local val = unpack_uint32(str, offset)\n"
"    if val >= 0x80000000 then return val - 0x100000000 end\n"
"    return val\n"
"end\n"
"\n"
"function sbank(bank_id)\n"
"    poke(ADDR_BANK_SWITCH, bank_id or 0)\n"
"end\n"
"\n"
"-- Upgraded Asset Loader supporting dynamic targets: sprsht(\"sprites.bmp\", 0)\n"
"function sprsht(filename, bank_id)\n"
"    bank_id = bank_id or 0\n"
"    local dest_ram_address = BANK_ADDRESSES[bank_id]\n"
"    \n"
"    if not dest_ram_address then\n"
"        print(\"Error: Invalid Bank ID selection: \" .. tostring(bank_id))\n"
"        return false\n"
"    end\n"
"\n"
"    local file = io.open(filename, \"rb\")\n"
"    if not file then return false end\n"
"\n"
"    local header = file:read(54)\n"
"    if not header or string.sub(header, 1, 2) ~= \"BM\" then\n"
"        file:close()\n"
"        return false\n"
"    end\n"
"\n"
"    local pixel_data_offset = unpack_uint32(header, 11)\n"
"    local width              = unpack_int32(header, 19)\n"
"    local height             = unpack_int32(header, 23)\n"
"    local bits_per_pixel     = string.byte(header, 29) + (string.byte(header, 30) << 8)\n"
"\n"
"    file:seek(\"set\", pixel_data_offset)\n"
"\n"
"    local abs_height = math.abs(height)\n"
"    local is_bottom_up = (height > 0)\n"
"\n"
"    if bits_per_pixel == 24 then\n"
"        local row_size = math.floor(((24 * width) + 31) / 32) * 4\n"
"        local pixel_bytes = file:read(row_size * abs_height)\n"
"        file:close()\n"
"\n"
"		if width > 64 or abs_height > 64 then\n"
"        		print(string.format(\"CRITICAL ERROR: '%s' is %dx%d. Max spritesheet dimensions allowed: 64x64!\", \n"
"            		filename, width, abs_height))\n"
"        		return false\n"
"    		end\n"
"\n"
"        -- Dynamically log the true sheet proportions so our spr() renderer can adapt!\n"
"        BANK_WIDTHS[bank_id]  = width\n"
"        BANK_HEIGHTS[bank_id] = abs_height\n"
"\n"
"        for y = 0, abs_height - 1 do\n"
"            local bmp_y = is_bottom_up and (abs_height - 1 - y) or y\n"
"            local row_start = (bmp_y * row_size) + 1\n"
"\n"
"            for x = 0, width - 1 do\n"
"                local byte_pos = row_start + (x * 3)\n"
"                local b = string.byte(pixel_bytes, byte_pos)\n"
"                local g = string.byte(pixel_bytes, byte_pos + 1)\n"
"                local r = string.byte(pixel_bytes, byte_pos + 2)\n"
"\n"
"                local color16 = rgb(r, g, b)\n"
"\n"
"                -- Calculate absolute destination index sequentially\n"
"                local target_ram_addr = dest_ram_address + ((y * width + x) * 2)\n"
"                poke(target_ram_addr,     color16 & 0xFF)\n"
"                poke(target_ram_addr + 1, (color16 >> 8) & 0xFF)\n"
"            end\n"
"        end\n"
"    else\n"
"        print(\"Error: Save asset sprites as 24-bit BMP.\")\n"
"        file:close()\n"
"        return false\n"
"    end\n"
"\n"
"    -- print(\"Loaded \" .. filename .. \" (\" .. width .. \"x\" .. abs_height .. \") into Sprite Bank \" .. bank_id)\n"
"    return true\n"
"end\n"
"\n"
"-- Upgraded 16-Bit Sprite Renderer that scales beautifully to fit 64x64 grids\n"
"function spr(id, screen_x, screen_y, flip_x, flip_y)\n"
"    local current_bank = peek(ADDR_BANK_SWITCH)\n"
"    \n"
"    local sprite_sheet_base  = BANK_ADDRESSES[current_bank] or 0x06500\n"
"    local sprite_sheet_width = BANK_WIDTHS[current_bank] or 64\n"
"\n"
"    -- Calculate how many 8x8 sprite columns fit across this specific sheet width\n"
"    local total_cols = math.floor(sprite_sheet_width / 8)\n"
"\n"
"    local spr_x = (id % total_cols) * 8\n"
"    local spr_y = math.floor(id / total_cols) * 8\n"
"\n"
"    for py = 0, 7 do\n"
"        for px = 0, 7 do\n"
"            local source_x = spr_x + (flip_x and (7 - px) or px)\n"
"            local source_y = spr_y + (flip_y and (7 - py) or py)\n"
"\n"
"            local source_addr = sprite_sheet_base + ((source_y * sprite_sheet_width + source_x) * 2)\n"
"            local low = peek(source_addr)\n"
"            local high = peek(source_addr + 1)\n"
"            local color16 = low | (high << 8)\n"
"\n"
"            -- Treat pure absolute black (0x0000) as transparent!\n"
"            if color16 ~= 0x0000 then\n"
"                pset(screen_x + px, screen_y + py, color16)\n"
"            end\n"
"        end\n"
"    end\n"
"end\n"
"\n"
"--text/font rendering\n"
"-- TODO: update character map for special characters+\n"
"local ASCII_TO_FONT_INDEX = {}\n"
"local sequential_chars = \"ABCDEFGHIJKLMNOPQRSTUVWXYZ !__0123456789.:(){}-+/*,=\\\"'_[]____?<>@#$%^__~\"\n"
"\n"
"for i = 1, #sequential_chars do\n"
"    local b = sequential_chars:byte(i)\n"
"    ASCII_TO_FONT_INDEX[b] = i - 1\n"
"end\n"
"\n"
"ASCII_TO_FONT_INDEX[string.byte(\"_\")] = 43  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"[\")] = 44  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"]\")] = 45  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"{\")] = 47  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"}\")] = 48  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"^\")] = 49  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"?\")] = 50  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"<\")] = 51  \n"
"ASCII_TO_FONT_INDEX[string.byte(\">\")] = 52  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"@\")] = 53  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"#\")] = 54  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"$\")] = 55  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"%\")] = 56  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"&\")] = 57  \n"
"ASCII_TO_FONT_INDEX[string.byte(\"~\")] = 58  \n"
"\n"
"local function get_char_width(font_char_addr)\n"
"    local max_col = 0\n"
"    for row = 0, 4 do\n"
"        local row_byte = peek(font_char_addr + row)\n"
"        for col = 0, 4 do\n"
"            local bit_mask = 0x80 >> col\n"
"            if (row_byte & bit_mask) ~= 0 then\n"
"                if col > max_col then max_col = col end\n"
"            end\n"
"        end\n"
"    end\n"
"    if max_col == 0 then return 2 end\n"
"    return max_col + 1\n"
"end\n"
"\n"
"-- 16-Bit Variant Text Printer\n"
"function text(str, x, y, color)\n"
"    if PALETTE[color] then\n"
"        color = PALETTE[color]\n"
"    end\n"
"    -- Default to pure white color if no value is explicitly declared\n"
"    color = color or rgb(255, 255, 255)\n"
"    local start_x = x\n"
"\n"
"    str = string.upper(str)\n"
"\n"
"    for i = 1, #str do\n"
"        local byte_code = str:byte(i)\n"
"        \n"
"        if byte_code == 10 then \n"
"            x = start_x\n"
"            y = y + 6 \n"
"        else\n"
"            local idx = ASCII_TO_FONT_INDEX[byte_code]\n"
"            if idx then\n"
"                local font_char_addr = ADDR_FONT + (idx * 6)\n"
"                local char_width = get_char_width(font_char_addr)\n"
"                \n"
"                for row = 0, 4 do\n"
"                    local row_byte = peek(font_char_addr + row)\n"
"                    for col = 0, char_width - 1 do\n"
"                        local bit_mask = 0x80 >> col\n"
"                        \n"
"                        if (row_byte & bit_mask) ~= 0 then\n"
"                            -- Draw using our newly updated 16-bit pset!\n"
"                            pset(x + col, y + row, color)\n"
"                        end\n"
"                    end\n"
"                end\n"
"                x = x + char_width + 1\n"
"            else\n"
"                x = x + 4\n"
"            end\n"
"        end\n"
"    end\n"
"end\n";

const char* APU_SOURCE = 
"-- runtime/apu.lua\n"
"\n"
"local ADDR_AUDIO = 0x06050\n"
"local function CH_STATUS(ch)  return ADDR_AUDIO + (ch * 10) + 0 end\n"
"local function CH_TRIGGER(ch) return ADDR_AUDIO + (ch * 10) + 1 end\n"
"local function CH_LOOP(ch)    return ADDR_AUDIO + (ch * 10) + 2 end\n"
"local function CH_ADDR_0(ch)  return ADDR_AUDIO + (ch * 10) + 3 end\n"
"local function CH_ADDR_1(ch)  return ADDR_AUDIO + (ch * 10) + 4 end\n"
"local function CH_ADDR_2(ch)  return ADDR_AUDIO + (ch * 10) + 5 end\n"
"local function CH_LEN_0(ch)   return ADDR_AUDIO + (ch * 10) + 6 end\n"
"local function CH_LEN_1(ch)   return ADDR_AUDIO + (ch * 10) + 7 end\n"
"local function CH_LEN_2(ch)   return ADDR_AUDIO + (ch * 10) + 8 end\n"
"local function CH_VOLUME(ch)  return ADDR_AUDIO + (ch * 10) + 9 end\n"
"\n"
"-- Helper functions to unpack little-endian integers from a binary string\n"
"local function unpack_u16(str, offset)\n"
"    local b1, b2 = string.byte(str, offset, offset + 1)\n"
"    return b1 + (b2 << 8)\n"
"end\n"
"\n"
"local function unpack_u32(str, offset)\n"
"    local b1, b2, b3, b4 = string.byte(str, offset, offset + 3)\n"
"    return b1 + (b2 << 8) + (b3 << 16) + (b4 << 24)\n"
"end\n"
"\n"
"function sfx(filename, volume, channel)\n"
"    channel = channel or 2\n"
"    volume = math.floor((volume or 1.0) * 255)\n"
"    if volume > 255 then volume = 255 end\n"
"\n"
"    local file = io.open(filename, \"rb\")\n"
"    if not file then return false end\n"
"\n"
"    -- Read file and parse data size\n"
"    local current = file:seek()\n"
"    local file_size = file:seek(\"end\")\n"
"    file:seek(\"set\", current)\n"
"    local header = file:read(44)\n"
"    local data_size = file_size - 44\n"
"    local pcm_data = file:read(data_size)\n"
"    file:close()\n"
"\n"
"    -- Calculate destination relative to the new ADDR_SNDBUF location\n"
"    local addr_sndbuf = 0x0A500\n"
"    local audio_ram_dest = addr_sndbuf + (channel * 0x8000) -- 32KB shifts\n"
"\n"
"    -- Safety check at 32KB\n"
"    if data_size > 32768 then data_size = 32768 end \n"
"\n"
"    -- Poke the raw payload bytes into the high memory bank\n"
"    for i = 1, data_size do\n"
"        local u8_sample = string.byte(pcm_data, i)\n"
"        poke(audio_ram_dest + (i - 1), u8_sample)\n"
"    end\n"
"\n"
"    -- Clear trailing buffer space to silent center (128)\n"
"    for i = data_size, 32768 do\n"
"        poke(audio_ram_dest + i, 128)\n"
"    end\n"
"\n"
"    -- Register packing math\n"
"    local addr_high = (audio_ram_dest >> 16) & 0xFF\n"
"    local addr_mid  = (audio_ram_dest >> 8) & 0xFF\n"
"    local addr_low  = audio_ram_dest & 0xFF\n"
"\n"
"    local len_high = math.floor(data_size / 65536) & 0xFF\n"
"    local len_mid  = math.floor(data_size / 256) & 0xFF\n"
"    local len_low  = data_size & 0xFF\n"
"\n"
"    -- Fire away!\n"
"    poke(CH_VOLUME(channel), volume)\n"
"    poke(CH_ADDR_0(channel), addr_high)\n"
"    poke(CH_ADDR_1(channel), addr_mid)\n"
"    poke(CH_ADDR_2(channel), addr_low)\n"
"    poke(CH_LEN_0(channel),  len_high)\n"
"    poke(CH_LEN_1(channel),  len_mid)\n"
"    poke(CH_LEN_2(channel),  len_low)\n"
"    poke(CH_LOOP(channel),   0)\n"
"    poke(CH_STATUS(channel), 1)\n"
"    poke(CH_TRIGGER(channel), 1)\n"
"\n"
"    return true\n"
"end\n"
"\n"
"-- Define the exact hex addresses matching the C side definitions\n"
"local IO_TRACKER_ENABLED = 0x06092 -- Swap this hex number with your exact calculation if needed!\n"
"local IO_TRACKER_VOLUME  = 0x06093\n"
"\n"
"Tracker = {\n"
"    is_playing = false,\n"
"    volume = 1.0,\n"
"    fade_target = 1.0,\n"
"    fade_speed = 0.0,\n"
"    fade_callback = nil\n"
"}\n"
"\n"
"function module_load(filename)\n"
"    feed_tracker(filename) -- Call our clean native C asset loading function wrapper\n"
"    Tracker.is_playing = false\n"
"    Tracker.volume = 1.0\n"
"    \n"
"    poke(IO_TRACKER_ENABLED, 0)\n"
"    poke(IO_TRACKER_VOLUME, 255) \n"
"end\n"
"\n"
"function module_play()\n"
"    Tracker.is_playing = true\n"
"    poke(IO_TRACKER_ENABLED, 1) -- Set hardware flag high! C takes over completely!\n"
"end\n"
"\n"
"function module_pause()\n"
"    Tracker.is_playing = false\n"
"    poke(IO_TRACKER_ENABLED, 0) -- Drop flag low to pause stream immediately\n"
"end\n"
"\n"
"function module_fade(target_volume, duration_frames, on_complete)\n"
"    Tracker.fade_target = target_volume\n"
"    Tracker.fade_callback = on_complete\n"
"    \n"
"    if duration_frames <= 0 then\n"
"        Tracker.volume = target_volume\n"
"        poke(IO_TRACKER_VOLUME, math.floor(target_volume * 255))\n"
"    else\n"
"        Tracker.fade_speed = (target_volume - Tracker.volume) / duration_frames\n"
"    end\n"
"end\n"
"\n"
"function module_tick()\n"
"    -- Process the creative fading loop updates\n"
"    if Tracker.volume ~= Tracker.fade_target then\n"
"        Tracker.volume = Tracker.volume + Tracker.fade_speed\n"
"        \n"
"        if (Tracker.fade_speed > 0 and Tracker.volume >= Tracker.fade_target) or\n"
"           (Tracker.fade_speed < 0 and Tracker.volume <= Tracker.fade_target) then\n"
"            Tracker.volume = Tracker.fade_target\n"
"            Tracker.fade_speed = 0\n"
"            \n"
"            if Tracker.fade_callback then \n"
"                Tracker.fade_callback() \n"
"                Tracker.fade_callback = nil\n"
"            end\n"
"        end\n"
"        \n"
"        local raw_u8_vol = math.floor(Tracker.volume * 255)\n"
"        if raw_u8_vol > 255 then raw_u8_vol = 255 end\n"
"        if raw_u8_vol < 0   then raw_u8_vol = 0 end\n"
"        poke(IO_TRACKER_VOLUME, raw_u8_vol)\n"
"    end\n"
"end\n";

const char* BATUTTA_SOURCE = 
"local ADDR_MAP   = 0x2A500  -- Updated base memory pointer to map space \n"
"local MAP_WIDTH  = 256\n"
"local MAP_HEIGHT = 192\n"
"\n"
"function tile(x, y, tile_num)\n"
"    if x < 0 or x >= MAP_WIDTH or y < 0 or y >= MAP_HEIGHT then\n"
"        if tile_num == nil then return 0 end\n"
"        return\n"
"    end\n"
"\n"
"    local target_address = ADDR_MAP + (y * MAP_WIDTH + x)\n"
"\n"
"    if tile_num == nil then\n"
"        return peek(target_address)\n"
"    else\n"
"        poke(target_address, tile_num & 0xFF)\n"
"    end\n"
"end\n"
"\n"
"function mget(x, y)\n"
"    return tile(x, y)\n"
"end\n"
"\n"
"function mset(x, y, tile_num)\n"
"    tile(x, y, tile_num)\n"
"end\n"
"\n"
"function map(start_tile_x, start_tile_y, screen_x, screen_y, tiles_w, tiles_h)\n"
"    -- Fallback: If no width/height are specified, default to what fits on the screen\n"
"    -- 128 / 8 = 16 tiles wide, 96 / 8 = 12 tiles high\n"
"    tiles_w = tiles_w or 16\n"
"    tiles_h = tiles_h or 12\n"
"    \n"
"    for ty = 0, tiles_h - 1 do\n"
"        local map_y = start_tile_y + ty\n"
"        for tx = 0, tiles_w - 1 do\n"
"            local map_x = start_tile_x + tx\n"
"            \n"
"            -- Grab the sprite ID assigned to this grid coordinate\n"
"            local sprite_id = mget(map_x, map_y)\n"
"            \n"
"            -- Only draw if it's a visible, non-zero sprite (treating 0 as transparent/empty sky)\n"
"            if sprite_id > 0 then\n"
"                -- Calculate the absolute world coordinates where this tile should be drawn\n"
"                local draw_x = screen_x + (tx * 8)\n"
"                local draw_y = screen_y + (ty * 8)\n"
"                \n"
"                -- Pass it to your existing spr() renderer!\n"
"                spr(sprite_id, draw_x, draw_y)\n"
"            end\n"
"        end\n"
"    end\n"
"end\n";

const char* JOYPADS_SOURCE = 
"-- Hardware Addresses (16-bit layout)\n"
"local ADDR_INP_CURRENT_LOW   = 0x06040\n"
"local ADDR_INP_CURRENT_HIGH  = 0x06041\n"
"local ADDR_INP_PREVIOUS_LOW  = 0x06042\n"
"local ADDR_INP_PREVIOUS_HIGH = 0x06043\n"
"\n"
"-- Maps to the bit offsets\n"
"BTN_LEFT  = 0  -- (1 << 0)\n"
"BTN_RIGHT = 1  -- (1 << 1)\n"
"BTN_UP    = 2  -- (1 << 2)\n"
"BTN_DOWN  = 3  -- (1 << 3)\n"
"BTN_A     = 4  -- (1 << 4)\n"
"BTN_B     = 5  -- (1 << 5)\n"
"BTN_C     = 6  -- (1 << 6)\n"
"BTN_D     = 7  -- (1 << 7)\n"
"BTN_ENTER = 8  -- (1 << 8)\n"
"\n"
"-- Reconstructs the 16-bit word from memory maps dynamically\n"
"local function get_current_mask()\n"
"    return peek(ADDR_INP_CURRENT_LOW) | (peek(ADDR_INP_CURRENT_HIGH) << 8)\n"
"end\n"
"\n"
"local function get_previous_mask()\n"
"    return peek(ADDR_INP_PREVIOUS_LOW) | (peek(ADDR_INP_PREVIOUS_HIGH) << 8)\n"
"end\n"
"\n"
"--- Checks if a button is currently held down\n"
"function btn(id)\n"
"    local current = get_current_mask()\n"
"    return (current & (1 << id)) ~= 0\n"
"end\n"
"\n"
"--- Checks if a button was pressed THIS frame, but not last frame\n"
"function btnp(id)\n"
"    local current  = get_current_mask()\n"
"    local previous = get_previous_mask()\n"
"    \n"
"    local is_down_now = (current & (1 << id)) ~= 0\n"
"    local was_up_then = (previous & (1 << id)) == 0\n"
"    \n"
"    return is_down_now and was_up_then\n"
"end\n";

const char* SHORTHAND_SOURCE = 
"-- runtime/essentials.lua\n"
"-- nothing special, just simple lua wrappers\n"
"\n"
"function clamp(val, min, max)\n"
"    return math.max(min, math.min(max, val))\n"
"end\n"
"\n"
"function sin(x)\n"
"    return math.sin(x)\n"
"end\n"
"\n"
"function cos(x)\n"
"    return math.cos(x)\n"
"end\n"
"\n"
"function tan(x)\n"
"	return math.tan(x)\n"
"end\n"
"\n"
"function flr(x)\n"
"	return math.floor(x)\n"
"end\n"
"\n"
"function ceil(x)\n"
"	return math.ceil(x)\n"
"end\n"
"\n"
"function min(x, num)\n"
"	return math.min(x, num)\n"
"end\n"
"\n"
"function max(x)\n"
"	return math.max(x)\n"
"end\n"
"\n"
"function mid(x, y, z)\n"
"    return math.max(math.min(x, y), math.min(math.max(x, y), z))\n"
"end\n"
"\n"
"function sqrt(x)\n"
"	return math.sqrt(x)\n"
"end\n"
"\n"
"function add(table, object)\n"
"	return table.insert(table, object)\n"
"end\n"
"\n"
"function t()\n"
"    return os.clock()\n"
"end\n";

#endif
